config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  
  resources :pictures do
    collection do
      post :comfirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :content, presence: true
  validates :image, presence: true

  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_secure_password
  
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  def index
    @pictures = current_user.pictures
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def create
    @picture = current_user.pictures.new(picture_params)
    if @picture.save
      redirect_to pictures_path, notice: "作成しました！"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_url, notice: "削除しました。"
  end

  def comfirm
    @picture = current_user.pictures.new(picture_params)
  end

  private
  
  def picture_params
    params.require(:picture).permit(:content, :image, :image_cache, :user_id)
  end

  def set_picture
    @picture = current_user.pictures.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: session_params[:email].downcase)
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to pictures_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました!!!'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました!!!'
    redirect_to new_session_path
  end

  private
  def session_params
    params.require(:session).permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def show
    @user = User.find(params[:id])
    end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to user_path(@user.id)
    else
        render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new
    if action_name == 'new'
      comfirm_pictures_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
      current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <img src="/assets/Facebook.png" alt="">
      <hr>
    </header>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "登録内容", user_path(current_user.id) %>
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "新しく作る", new_user_path %>
      <%= link_to "ログイン", new_session_path %>
    <% end %>

      <%= yield %>
    <footer>
    
      <hr>
      <img src="/assets/Facebook.png" alt="">
    </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url: choose_new) do |form| %>

  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
    <%= form.label :image %>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to "投稿一覧画面にもどる", pictures_path %>

app/views/pictures/comfirm.html.erb
<h2>確認画面</h2>
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.hidden_field :image_cache %>
  <p>本文:<%= @picture.content %></p>
  <%= form.submit "投稿する" %>
<% end %>
<%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/pictures/edit.html.erb
  <h2>投稿を編集する</h2>
  <%= render 'form' %>

app/views/pictures/index.html.erb
<h2>「<%= current_user.name %>」のページ</h2>
<table>
  <tr>
    <th>投稿一覧</th>
    <th>投稿画像</th>
    <th>ユーザー名</th>
  </tr>
<% @pictures.each do |picture| %>
  <tr>
    <td><%= picture.content %></td>
    <td><%= picture.image %></td>
    <td><%= picture.user.name %></td>
    <td><%= link_to '投稿の詳細', picture_path(picture.id), class:"btn btn-secondary" %></td>
    <td><%= link_to "投稿を編集", edit_picture_path(picture.id), class:"btn btn-secondary" %></td>
    <td><%= link_to '投稿を削除', picture_path(picture.id), class:"btn btn-secondary", method: :delete, data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</table>
<br>
<%= link_to '新しく投稿する', new_picture_path, class:"btn btn-primary" %>

app/views/pictures/new.html.erb
<h2>投稿を作成する</h2>
<%= render 'form' %>

app/views/pictures/show.html.erb
<h1>投稿詳細画面</h1>
<h2>
	内容：
	<%= @picture.content %>
	画像：
	<%= image_tag @picture.image.url %>
</h2>

<%= link_to '戻る', pictures_path %>

app/views/users/new.html.erb
<h1>アカウント作成</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit "アカウントを作成する" %>
<% end %>

app/views/users/show.html.erb
<p>ログインに成功しました！！！</p>

<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>

<%= link_to '投稿一覧', pictures_path, class:"btn btn-primary" %>